---
- hosts: es_0
  vars:
    debian_common_admin_user_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMDwryfdeKGbVeC+jMB5VjGLa8X6ai9S3dThl9fATjxewOJoF8rkwCTMNqs056JyMAUungSJsoEfLDMzTwt4tDHyNf4jNiIRhAuvjjyzkV1UlNI1UsGrxUFFWNQuQEO5CpomMzspmhyfeej6RiTzN+D+4le59d/0jg/LABnVDbrbCXbiUmQALGrAhlxfDji5gahirnCGVthz5SwB/SsafWHL64aWV4MF7yZVCUwyAw1LU3ei3vd1yPKculzFnTY8SEeMJlapPWMDOfZp82Wzrj6WKaD8DWoMzGTGIduM28bMQgi7PDhp4ozUlCBzbMGgsE6g48TeE7L8S2N3rNtK3oftaXDH4Lo1fAcATD6JRiuKj/d79Dh/jIBoYrwxNu6dPFIFYpW7Qz2SzRfeGKiHuv+h9aX6N/7/mEykkFrD3XswJBnd4ybi1HZGiJdkewBbiOJnwoJiYcTIQpc2Qt8X1E59uHvWLEVFKffo7H67VrNSjiGrW1wb/nLFIsbHHol3bolBkcUVb3IO8VsxI869J8v29TZ1VL2etnWpepdzYHDhKwON5ub62czPvH9hn/iDKBxdPaxWFJiW6l8GlKWbcXCjWe2PiSk/cAaRSJfKqkP87gGJJm5FWEwKQ5TLkpv7n4fMTM5OydbjDAEaNsfyaGTf9ZFMHMLUJaN3Qjnstupw== wael@arkops.io
  roles:
    - role: debian-common
      prebootstrap: true
      become: true
    - role: debian-common
      bootstrap: true
      add_remove_keys: true
      vars:
        ports: ["22", "9300", "9200"]
    - role: elastic
      vars:
        # es_version: 7.16.2
        es_config:
          node.name: "es_0"
          cluster.name: "test-cluster"
          # discovery.seed_hosts: "{{ groups['elk'] | map('extract', hostvars, ['ansible_host']) | join(':9300,') }}:9300"
          # cluster.initial_master_nodes: "{{ groups['elk'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
          discovery.seed_hosts: "163.172.159.6:9300"
          cluster.initial_master_nodes: "es_0"
          http.host: 0.0.0.0
          http.port: 9200
          transport.host: 0.0.0.0
          transport.port: 9300
          node.data: false
          node.master: true
          bootstrap.memory_lock: true
          xpack.security.authc.realms.file.file1.order: 0
          xpack.security.authc.realms.native.native1.order: 1
        es_heap_size: 1g
        es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
        es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_keystore: "./elastic-tls/keystore/es_0/es_0.p12"
        es_ssl_truststore: "./elastic-tls/my-ca.p12"
        # es_ssl_truststore_password: "secret"
        # es_ssl_keystore_password: "secret"
        es_validate_certs: no

- hosts: es_1
  vars:
    debian_common_admin_user_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMDwryfdeKGbVeC+jMB5VjGLa8X6ai9S3dThl9fATjxewOJoF8rkwCTMNqs056JyMAUungSJsoEfLDMzTwt4tDHyNf4jNiIRhAuvjjyzkV1UlNI1UsGrxUFFWNQuQEO5CpomMzspmhyfeej6RiTzN+D+4le59d/0jg/LABnVDbrbCXbiUmQALGrAhlxfDji5gahirnCGVthz5SwB/SsafWHL64aWV4MF7yZVCUwyAw1LU3ei3vd1yPKculzFnTY8SEeMJlapPWMDOfZp82Wzrj6WKaD8DWoMzGTGIduM28bMQgi7PDhp4ozUlCBzbMGgsE6g48TeE7L8S2N3rNtK3oftaXDH4Lo1fAcATD6JRiuKj/d79Dh/jIBoYrwxNu6dPFIFYpW7Qz2SzRfeGKiHuv+h9aX6N/7/mEykkFrD3XswJBnd4ybi1HZGiJdkewBbiOJnwoJiYcTIQpc2Qt8X1E59uHvWLEVFKffo7H67VrNSjiGrW1wb/nLFIsbHHol3bolBkcUVb3IO8VsxI869J8v29TZ1VL2etnWpepdzYHDhKwON5ub62czPvH9hn/iDKBxdPaxWFJiW6l8GlKWbcXCjWe2PiSk/cAaRSJfKqkP87gGJJm5FWEwKQ5TLkpv7n4fMTM5OydbjDAEaNsfyaGTf9ZFMHMLUJaN3Qjnstupw== wael@arkops.io
  roles:
    - role: debian-common
      prebootstrap: true
      become: true
    - role: debian-common
      bootstrap: true
      add_remove_keys: true
      vars:
        ports: ["22", "9300", "9200"]
    - role: elastic
      vars:
        # es_version: 7.16.2
        es_config:
          node.name: "es_1"
          cluster.name: "test-cluster"
          discovery.seed_hosts: "163.172.159.6:9300"
          cluster.initial_master_nodes: "es_0"
          http.host: 0.0.0.0
          http.port: 9200
          transport.host: 0.0.0.0
          transport.port: 9300
          node.data: true
          node.master: false
          bootstrap.memory_lock: true
          xpack.security.authc.realms.file.file1.order: 0
          xpack.security.authc.realms.native.native1.order: 1
        es_heap_size: 1g
        es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
        es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_keystore: "./elastic-tls/keystore/es_1/es_1.p12"
        es_ssl_truststore: "./elastic-tls/my-ca.p12"
        # es_ssl_truststore_password: "secret"
        # es_ssl_keystore_password: "secret"
        es_validate_certs: no

- hosts: es_2
  vars:
    debian_common_admin_user_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMDwryfdeKGbVeC+jMB5VjGLa8X6ai9S3dThl9fATjxewOJoF8rkwCTMNqs056JyMAUungSJsoEfLDMzTwt4tDHyNf4jNiIRhAuvjjyzkV1UlNI1UsGrxUFFWNQuQEO5CpomMzspmhyfeej6RiTzN+D+4le59d/0jg/LABnVDbrbCXbiUmQALGrAhlxfDji5gahirnCGVthz5SwB/SsafWHL64aWV4MF7yZVCUwyAw1LU3ei3vd1yPKculzFnTY8SEeMJlapPWMDOfZp82Wzrj6WKaD8DWoMzGTGIduM28bMQgi7PDhp4ozUlCBzbMGgsE6g48TeE7L8S2N3rNtK3oftaXDH4Lo1fAcATD6JRiuKj/d79Dh/jIBoYrwxNu6dPFIFYpW7Qz2SzRfeGKiHuv+h9aX6N/7/mEykkFrD3XswJBnd4ybi1HZGiJdkewBbiOJnwoJiYcTIQpc2Qt8X1E59uHvWLEVFKffo7H67VrNSjiGrW1wb/nLFIsbHHol3bolBkcUVb3IO8VsxI869J8v29TZ1VL2etnWpepdzYHDhKwON5ub62czPvH9hn/iDKBxdPaxWFJiW6l8GlKWbcXCjWe2PiSk/cAaRSJfKqkP87gGJJm5FWEwKQ5TLkpv7n4fMTM5OydbjDAEaNsfyaGTf9ZFMHMLUJaN3Qjnstupw== wael@arkops.io
  roles:
    - role: debian-common
      prebootstrap: true
      become: true
    - role: debian-common
      bootstrap: true
      add_remove_keys: true
      vars:
        ports: ["22", "9300", "9200"]
    - role: elastic
      vars:
        # es_version: 7.16.2
        es_config:
          node.name: "es_2"
          cluster.name: "test-cluster"
          discovery.seed_hosts: "163.172.159.6:9300"
          cluster.initial_master_nodes: "es_0"
          http.host: 0.0.0.0
          http.port: 9200
          transport.host: 0.0.0.0
          transport.port: 9300
          node.data: true
          node.master: false
          bootstrap.memory_lock: true
          xpack.security.authc.realms.file.file1.order: 0
          xpack.security.authc.realms.native.native1.order: 1
        es_heap_size: 1g
        es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
        es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
        es_enable_http_ssl: true
        es_enable_transport_ssl: true
        es_ssl_keystore: "./elastic-tls/keystore/es_2/es_2.p12"
        es_ssl_truststore: "./elastic-tls/my-ca.p12"
        # es_ssl_truststore_password: "secret"
        # es_ssl_keystore_password: "secret"
        es_validate_certs: no

- hosts: grafana
  vars:
    debian_common_admin_user_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMDwryfdeKGbVeC+jMB5VjGLa8X6ai9S3dThl9fATjxewOJoF8rkwCTMNqs056JyMAUungSJsoEfLDMzTwt4tDHyNf4jNiIRhAuvjjyzkV1UlNI1UsGrxUFFWNQuQEO5CpomMzspmhyfeej6RiTzN+D+4le59d/0jg/LABnVDbrbCXbiUmQALGrAhlxfDji5gahirnCGVthz5SwB/SsafWHL64aWV4MF7yZVCUwyAw1LU3ei3vd1yPKculzFnTY8SEeMJlapPWMDOfZp82Wzrj6WKaD8DWoMzGTGIduM28bMQgi7PDhp4ozUlCBzbMGgsE6g48TeE7L8S2N3rNtK3oftaXDH4Lo1fAcATD6JRiuKj/d79Dh/jIBoYrwxNu6dPFIFYpW7Qz2SzRfeGKiHuv+h9aX6N/7/mEykkFrD3XswJBnd4ybi1HZGiJdkewBbiOJnwoJiYcTIQpc2Qt8X1E59uHvWLEVFKffo7H67VrNSjiGrW1wb/nLFIsbHHol3bolBkcUVb3IO8VsxI869J8v29TZ1VL2etnWpepdzYHDhKwON5ub62czPvH9hn/iDKBxdPaxWFJiW6l8GlKWbcXCjWe2PiSk/cAaRSJfKqkP87gGJJm5FWEwKQ5TLkpv7n4fMTM5OydbjDAEaNsfyaGTf9ZFMHMLUJaN3Qjnstupw== wael@arkops.io
  roles:
    - role: debian-common
      prebootstrap: true
      become: true
    - role: debian-common
      bootstrap: true
      add_remove_keys: true
      vars:
        ports: ["22", "3000"]
    - role: grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: "funadmin"
        grafana_datasources:
          - name: Elastic
            type: elasticsearch
            access: proxy
            database: '[metrics-]YYYY.MM.DD'
            url: 'https://163.172.159.6:9200'
            basicAuth: true
            basicAuthUser: elastic
            basicAuthPassword: changeme
            jsonData:
              interval: Daily
              timeField: '@timestamp'
              tlsSkipVerify: true

- hosts: ralph
  vars:
    debian_common_admin_user_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMDwryfdeKGbVeC+jMB5VjGLa8X6ai9S3dThl9fATjxewOJoF8rkwCTMNqs056JyMAUungSJsoEfLDMzTwt4tDHyNf4jNiIRhAuvjjyzkV1UlNI1UsGrxUFFWNQuQEO5CpomMzspmhyfeej6RiTzN+D+4le59d/0jg/LABnVDbrbCXbiUmQALGrAhlxfDji5gahirnCGVthz5SwB/SsafWHL64aWV4MF7yZVCUwyAw1LU3ei3vd1yPKculzFnTY8SEeMJlapPWMDOfZp82Wzrj6WKaD8DWoMzGTGIduM28bMQgi7PDhp4ozUlCBzbMGgsE6g48TeE7L8S2N3rNtK3oftaXDH4Lo1fAcATD6JRiuKj/d79Dh/jIBoYrwxNu6dPFIFYpW7Qz2SzRfeGKiHuv+h9aX6N/7/mEykkFrD3XswJBnd4ybi1HZGiJdkewBbiOJnwoJiYcTIQpc2Qt8X1E59uHvWLEVFKffo7H67VrNSjiGrW1wb/nLFIsbHHol3bolBkcUVb3IO8VsxI869J8v29TZ1VL2etnWpepdzYHDhKwON5ub62czPvH9hn/iDKBxdPaxWFJiW6l8GlKWbcXCjWe2PiSk/cAaRSJfKqkP87gGJJm5FWEwKQ5TLkpv7n4fMTM5OydbjDAEaNsfyaGTf9ZFMHMLUJaN3Qjnstupw== wael@arkops.io
  roles:
    - role: debian-common
      prebootstrap: true
      become: true
    - role: debian-common
      bootstrap: true
      add_remove_keys: true
      vars:
        ports: ["22"]
    - role: pyenv
      vars:
        pyenv_owner: admin
        pyenv_virtualenvs:
          - venv_name: ralph_venv
            py_version: 3.9.15
    - role: ralph
      become_user: admin
      become: true