---
- import_tasks: custom_facts.yml
  become: true

- import_tasks: packages.yml
  become: true

- import_tasks: install.yml
  become: true
  become_user: "{{ pyenv_owner }}"
  when: pyenv_env == "user"

- import_tasks: install.yml
  become: true
  when: pyenv_env == "system"
