---
- name: Copy superset branding images.
  become: true
  become_user: "{{ superset_user }}"
  copy:
    src: "files/{{ item }}"
    dest: "{{ superset_base_path }}/static/assets/images/{{ item }}"
  with_items:
    - "{{ superset_favicon_path }}"
    - "{{ superset_logo_path }}"
    - "{{ superset_2x_logo_path }}"
  when: superset_white_label_use_filepaths|bool

- name: Decode and set up base64 encoded favicon
  shell: |
    set -o pipefail
    echo {{ superset_favicon_base64 }} | base64 -d > "{{ superset_base_path }}/static/assets/images/favicon.png"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ superset_user }}"
  when: superset_white_label_use_base64|bool

- name: Decode and set up base64 encoded logo
  shell: |
    set -o pipefail
    echo {{ superset_logo_base64 }} | base64 -d > "{{ superset_base_path }}/static/assets/images/superset.png"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ superset_user }}"
  when: superset_white_label_use_base64|bool

- name: Decode and set up base64 encoded @2x logo
  shell: |
    set -o pipefail
    echo {{ superset_2x_logo_base64 }} | base64 -d > "{{ superset_base_path }}/static/assets/images/{{ superset_2x_logo_filename }}"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ superset_user }}"
  when: superset_white_label_use_base64|bool

- name: Ensure Superset is restarted
  service: name=superset state=restarted
  when: superset_force_restart|bool
